// This file is auto-generated by @hey-api/openapi-ts

export type CreateExpositorSchema = {
    nome: string;
    descricao: string;
    rede_social: string;
};

export type CreateIngressoSchema = {
    nome: string;
    email: string;
    cpf: string;
};

export type CreatePecaSchema = {
    nome: string;
    preco: number;
    descricao?: string;
    reservada?: boolean;
    expositor_id: number;
};

export type ExpositorSchema = {
    id: number;
    nome: string;
    descricao?: string;
    rede_social?: string;
    created_by: UserSchema;
    created_at: string;
    updated_at: string;
};

export type ExpositorSchemaPatch = {
    id?: (number | null);
    nome?: (string | null);
    descricao?: (string | null);
    rede_social?: (string | null);
    created_by?: (UserSchema | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type IngressoSchema = {
    id: string;
    nome: string;
    email: string;
    cpf: string;
    data_compra: string;
    utilizado: boolean;
    data_utilizacao?: (string | null);
    created_by?: (string | null);
};

export type PecaSchema = {
    id: number;
    nome: string;
    preco: number;
    descricao?: string;
    reservada?: boolean;
    created_by: UserSchema;
    expositor_id: number;
    created_at: string;
    updated_at: string;
    expositor: number;
};

export type UpdatePecaSchema = {
    nome?: string;
    preco?: number;
    descricao?: string;
    reservada?: boolean;
    expositor_id?: number;
};

export type UserSchema = {
    id: string;
    name?: (string | null);
    email: string;
    image?: (string | null);
};

export type ValidateIngressoSchema = {
    ingresso_id: string;
    cpf: string;
};

export type AppApiListarExpositoresResponse = (Array<ExpositorSchema>);

export type AppApiCriarExpositorData = {
    requestBody: CreateExpositorSchema;
};

export type AppApiCriarExpositorResponse = (ExpositorSchema);

export type AppApiObterExpositorData = {
    expositorId: number;
};

export type AppApiObterExpositorResponse = (ExpositorSchema);

export type AppApiAtualizarExpositorData = {
    expositorId: number;
    requestBody: ExpositorSchemaPatch;
};

export type AppApiAtualizarExpositorResponse = (ExpositorSchema);

export type AppApiDeletarExpositorData = {
    expositorId: number;
};

export type AppApiDeletarExpositorResponse = (void);

export type AppApiListarPecasData = {
    expositorId?: number;
};

export type AppApiListarPecasResponse = (Array<PecaSchema>);

export type AppApiCriarPecaData = {
    requestBody: CreatePecaSchema;
};

export type AppApiCriarPecaResponse = (PecaSchema);

export type AppApiObterPecaData = {
    pecaId: number;
};

export type AppApiObterPecaResponse = (PecaSchema);

export type AppApiAtualizarPecaData = {
    pecaId: number;
    requestBody: UpdatePecaSchema;
};

export type AppApiAtualizarPecaResponse = (PecaSchema);

export type AppApiDeletarPecaData = {
    pecaId: number;
};

export type AppApiDeletarPecaResponse = (void);

export type AppApiCriarIngressoData = {
    requestBody: CreateIngressoSchema;
};

export type AppApiCriarIngressoResponse = (IngressoSchema);

export type AppApiGerarQrcodeData = {
    ingressoId: string;
};

export type AppApiGerarQrcodeResponse = (string);

export type AppApiValidarIngressoData = {
    requestBody: ValidateIngressoSchema;
};

export type AppApiValidarIngressoResponse = (IngressoSchema);

export type AppApiObterIngressoData = {
    ingressoId: string;
};

export type AppApiObterIngressoResponse = (IngressoSchema);