// This file is auto-generated by @hey-api/openapi-ts

export type CreateExpositorSchema = {
    nome: string;
    descricao: string;
    rede_social: string;
};

export type CreatePecaSchema = {
    nome: string;
    preco: number;
    descricao: string;
};

export type ExpositorSchema = {
    id: number;
    created_by: UserSchema;
    nome: string;
    descricao?: (string | null);
    rede_social?: (string | null);
    created_at: string;
    updated_at: string;
};

export type ExpositorSchemaPatch = {
    id?: (number | null);
    created_by?: (UserSchema | null);
    nome?: (string | null);
    descricao?: (string | null);
    rede_social?: (string | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type PecaSchema = {
    created_by: UserSchema;
    id?: (number | null);
    nome: string;
    preco: (number | string);
    descricao?: (string | null);
    expositor: number;
    created_at: string;
    updated_at: string;
};

export type PecaSchemaPatch = {
    created_by?: (UserSchema | null);
    id?: (number | null);
    nome?: (string | null);
    preco?: (number | string | null);
    descricao?: (string | null);
    expositor?: (number | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type UserSchema = {
    id: string;
    name?: (string | null);
    email: string;
    image?: (string | null);
};

export type AppApiListarExpositoresResponse = (Array<ExpositorSchema>);

export type AppApiCriarExpositorData = {
    requestBody: CreateExpositorSchema;
};

export type AppApiCriarExpositorResponse = (ExpositorSchema);

export type AppApiObterExpositorData = {
    expositorId: number;
};

export type AppApiObterExpositorResponse = (ExpositorSchema);

export type AppApiAtualizarExpositorData = {
    expositorId: number;
    requestBody: ExpositorSchemaPatch;
};

export type AppApiAtualizarExpositorResponse = (ExpositorSchema);

export type AppApiDeletarExpositorData = {
    expositorId: number;
};

export type AppApiDeletarExpositorResponse = (void);

export type AppApiListarPecasResponse = (Array<PecaSchema>);

export type AppApiCriarPecaData = {
    requestBody: CreatePecaSchema;
};

export type AppApiCriarPecaResponse = (PecaSchema);

export type AppApiObterPecaData = {
    pecaId: number;
};

export type AppApiObterPecaResponse = (PecaSchema);

export type AppApiAtualizarPecaData = {
    pecaId: number;
    requestBody: PecaSchemaPatch;
};

export type AppApiAtualizarPecaResponse = (PecaSchema);

export type AppApiDeletarPecaData = {
    pecaId: number;
};

export type AppApiDeletarPecaResponse = (void);