# Generated by Django 5.2.1 on 2025-06-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_verification_session_account_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peca',
            options={'ordering': ['created_at'], 'verbose_name': 'peca', 'verbose_name_plural': 'pecas'},
        ),
        migrations.AlterModelTable(
            name='peca',
            table='pecas',
        ),
    ]
