# Generated by Django 5.2.1 on 2025-06-10 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_peca_options_alter_peca_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='reservada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='peca',
            name='expositor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to='app.expositor'),
        ),
    ]
