# Generated by Django 5.2.1 on 2025-06-11 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_peca_reservada_alter_peca_expositor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peca',
            name='expositor',
            field=models.ForeignKey(db_column='expositor_id', on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to='app.expositor'),
        ),
    ]
