# Generated by Django 5.2.1 on 2025-06-12 01:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingresso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(11)])),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('utilizado', models.BooleanField(default=False)),
                ('data_utilizacao', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user')),
            ],
            options={
                'verbose_name': 'ingresso',
                'verbose_name_plural': 'ingressos',
                'db_table': 'ingressos',
                'ordering': ['-data_compra'],
            },
        ),
    ]
